### ISSUE TITLE
forward doesn't use it's first argument

### ISSUE THREAD

**Issue by oraoto** [cpuheater/pytorch_tutorials#4]
https://github.com/cpuheater/pytorch_examples/blob/b046ea92dc22cc07e5acaa77db55491b38497a48/elman_rnn/Elman_RNN.py#L30-L34

It doesn't use the `x` argument, but relies on `input` which is not in the scope of definiation. It's kind of confusing.

**Comment by cpuheater** [comment]
Yes, this should be input not x,  I've renamed it.  Thanks !
